// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: proto/draws.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Draw_Day int32

const (
	Draw_THURSDAY Draw_Day = 0
	Draw_FRIDAY   Draw_Day = 1
)

// Enum value maps for Draw_Day.
var (
	Draw_Day_name = map[int32]string{
		0: "THURSDAY",
		1: "FRIDAY",
	}
	Draw_Day_value = map[string]int32{
		"THURSDAY": 0,
		"FRIDAY":   1,
	}
)

func (x Draw_Day) Enum() *Draw_Day {
	p := new(Draw_Day)
	*p = x
	return p
}

func (x Draw_Day) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Draw_Day) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_draws_proto_enumTypes[0].Descriptor()
}

func (Draw_Day) Type() protoreflect.EnumType {
	return &file_proto_draws_proto_enumTypes[0]
}

func (x Draw_Day) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Draw_Day.Descriptor instead.
func (Draw_Day) EnumDescriptor() ([]byte, []int) {
	return file_proto_draws_proto_rawDescGZIP(), []int{0, 0}
}

type Draw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid       int32                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Number     int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Day        Draw_Day               `protobuf:"varint,3,opt,name=day,proto3,enum=draws.Draw_Day" json:"day,omitempty"`
	Cycle      int32                  `protobuf:"varint,4,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Forclusion *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=forclusion,proto3" json:"forclusion,omitempty"`
}

func (x *Draw) Reset() {
	*x = Draw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_draws_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Draw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Draw) ProtoMessage() {}

func (x *Draw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draws_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Draw.ProtoReflect.Descriptor instead.
func (*Draw) Descriptor() ([]byte, []int) {
	return file_proto_draws_proto_rawDescGZIP(), []int{0}
}

func (x *Draw) GetUuid() int32 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *Draw) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Draw) GetDay() Draw_Day {
	if x != nil {
		return x.Day
	}
	return Draw_THURSDAY
}

func (x *Draw) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *Draw) GetForclusion() *timestamppb.Timestamp {
	if x != nil {
		return x.Forclusion
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_draws_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draws_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_draws_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Draw *Draw `protobuf:"bytes,1,opt,name=draw,proto3" json:"draw,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_draws_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draws_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_draws_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetDraw() *Draw {
	if x != nil {
		return x.Draw
	}
	return nil
}

var File_proto_draws_proto protoreflect.FileDescriptor

var file_proto_draws_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x72, 0x61, 0x77, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x01, 0x0a, 0x04,
	0x44, 0x72, 0x61, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x21, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x2e, 0x44, 0x61, 0x79, 0x52, 0x03,
	0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x66, 0x6f, 0x72,
	0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x63, 0x6c,
	0x75, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x03, 0x44, 0x61, 0x79, 0x12, 0x0c, 0x0a, 0x08,
	0x54, 0x48, 0x55, 0x52, 0x53, 0x44, 0x41, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x52,
	0x49, 0x44, 0x41, 0x59, 0x10, 0x01, 0x22, 0x20, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x72, 0x61, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73, 0x2e, 0x44, 0x72,
	0x61, 0x77, 0x52, 0x04, 0x64, 0x72, 0x61, 0x77, 0x32, 0x37, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x77,
	0x73, 0x12, 0x2e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x72,
	0x61, 0x77, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_draws_proto_rawDescOnce sync.Once
	file_proto_draws_proto_rawDescData = file_proto_draws_proto_rawDesc
)

func file_proto_draws_proto_rawDescGZIP() []byte {
	file_proto_draws_proto_rawDescOnce.Do(func() {
		file_proto_draws_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_draws_proto_rawDescData)
	})
	return file_proto_draws_proto_rawDescData
}

var file_proto_draws_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_draws_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_draws_proto_goTypes = []interface{}{
	(Draw_Day)(0),                 // 0: draws.Draw.Day
	(*Draw)(nil),                  // 1: draws.Draw
	(*GetRequest)(nil),            // 2: draws.GetRequest
	(*GetResponse)(nil),           // 3: draws.GetResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_draws_proto_depIdxs = []int32{
	0, // 0: draws.Draw.day:type_name -> draws.Draw.Day
	4, // 1: draws.Draw.forclusion:type_name -> google.protobuf.Timestamp
	1, // 2: draws.GetResponse.draw:type_name -> draws.Draw
	2, // 3: draws.Draws.Get:input_type -> draws.GetRequest
	3, // 4: draws.Draws.Get:output_type -> draws.GetResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_draws_proto_init() }
func file_proto_draws_proto_init() {
	if File_proto_draws_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_draws_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Draw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_draws_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_draws_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_draws_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_draws_proto_goTypes,
		DependencyIndexes: file_proto_draws_proto_depIdxs,
		EnumInfos:         file_proto_draws_proto_enumTypes,
		MessageInfos:      file_proto_draws_proto_msgTypes,
	}.Build()
	File_proto_draws_proto = out.File
	file_proto_draws_proto_rawDesc = nil
	file_proto_draws_proto_goTypes = nil
	file_proto_draws_proto_depIdxs = nil
}
